from django.core.management.base import BaseCommand

from apps.stores.models import Site

HEADER = """# AUTO-GENERATED by `manage.py emit_nginx` — do not hand-edit.
# One server block per storefront. gunicorn listens on 127.0.0.1:8001.
# Regenerate whenever you add/remove a Site, then: nginx -t && systemctl reload nginx
"""

UPSTREAM = """upstream peptidenet_app { server 127.0.0.1:8001; }
"""

BLOCK = """
server {{
    listen 80;
    listen [::]:80;
    server_name {hosts};

    location /static/ {{ alias /var/www/peptidenet/staticfiles/; }}

    location / {{
        proxy_pass http://peptidenet_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""


class Command(BaseCommand):
    help = "Emit an nginx config with a server_name block for every active site."

    def handle(self, *args, **opts):
        out = [HEADER, UPSTREAM]
        for s in Site.objects.filter(is_active=True):
            out.append(BLOCK.format(hosts=" ".join(s.all_hostnames())))
        self.stdout.write("\n".join(out))
