from django.conf import settings
from django.core.management.base import BaseCommand

from apps.stores.models import Site

HEADER = """# AUTO-GENERATED by `manage.py emit_nginx` — do not hand-edit.
# One server block per storefront. gunicorn listens on 127.0.0.1:8001.
# Regenerate whenever you add/remove a Site, then: nginx -t && systemctl reload nginx
"""

UPSTREAM = """upstream peptidenet_app { server 127.0.0.1:8001; }

# Per-IP rate limit to blunt admin / control-panel login brute-forcing.
limit_req_zone $binary_remote_addr zone=pn_login:10m rate=10r/m;
"""

# Proxy directives, shared by every location that forwards to gunicorn.
PROXY = """        proxy_pass http://peptidenet_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;"""

BLOCK = """
server {{
    listen 80;
    listen [::]:80;
    server_name {hosts};

    server_tokens off;             # don't leak nginx version
    client_max_body_size 10m;      # cap request bodies

    # Far-future caching: asset URLs are versioned with ?v=<git-sha> (see
    # settings.ASSET_VERSION), so the URL changes whenever an asset changes —
    # making `immutable` + 1y safe and closing the Lighthouse "efficient cache
    # policy" gap. Durable here so a config regen never drops it.
    location /static/ {{
        alias /var/www/peptidenet/staticfiles/;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }}

    # Rate-limit the admin + control-panel to slow credential-stuffing.
    location /{admin} {{
        limit_req zone=pn_login burst=8 nodelay;
{proxy}
    }}
    location /manage/ {{
        limit_req zone=pn_login burst=12 nodelay;
{proxy}
    }}

    location / {{
{proxy}
    }}
}}
"""


class Command(BaseCommand):
    help = "Emit an nginx config with a server_name block for every active site."

    def handle(self, *args, **opts):
        admin = settings.ADMIN_PATH  # e.g. "admin/" or "ops-ab12cd/"
        # NOTE: the default-deny catch-all (bare IP / unknown hosts -> nginx 444)
        # lives in a standalone /etc/nginx/conf.d/00-default-deny.conf written by
        # deploy.sh / update.sh — NOT here — so regenerating this per-site config
        # can never collide with a second `default_server` on the same port.
        out = [HEADER, UPSTREAM]
        for s in Site.objects.filter(is_active=True):
            out.append(BLOCK.format(
                hosts=" ".join(s.all_hostnames()), admin=admin, proxy=PROXY,
            ))
        self.stdout.write("\n".join(out))
