"""Self-host Google Fonts: download woff2 to static/fonts/ and emit per-theme CSS.

  python manage.py fetch_webfonts          # download missing files + (re)write CSS
  python manage.py fetch_webfonts --force  # re-download every woff2

Run on the box after `git reset`, before collectstatic. The woff2 files and the
per-theme `<theme>.css` land in static/fonts/ (untracked, survive `git reset`,
collected by collectstatic), so the storefronts load fonts same-origin with no
render-blocking fonts.googleapis.com stylesheet and no cross-origin gstatic hop.
This command is the durable source of truth for the font set (mirrors emit_nginx).
"""
import re
import urllib.request
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

# One css2 URL per theme (&display=swap so each @font-face carries font-display).
#
# Typeface direction: clinical precision. Four themes previously ran Inter, which
# is the single most common "generated by an AI" tell in a font stack — it is the
# default everywhere, so it signals nothing. Each theme now runs a family with a
# point of view, chosen to fit that site's identity rather than to unify them.
#
# IBM Plex Mono ships with EVERY theme: it renders the spec tables, CAS numbers,
# amino-acid sequences, lot numbers and tracking codes. On a research-compound
# store, technical data set in a real engineered mono is the cheapest credibility
# the design can buy. base.css reads it via --font-mono.
_PLEX_MONO = "family=IBM+Plex+Mono:wght@400;500;600"

THEME_FONTS = {
    # Dark flagship, analytical rigour. Plex Sans is IBM's engineering typeface —
    # it reads as instrumentation, which is exactly the promise being made.
    "biolabs": "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&"
               + _PLEX_MONO + "&display=swap",
    # Light pharma, US market. Fraunces stays as the display voice; Plex Sans
    # replaces Inter underneath it.
    "clinical": "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&"
                "family=IBM+Plex+Sans:wght@400;500;600;700&" + _PLEX_MONO + "&display=swap",
    # Alberta. Instrument Sans is precise but slightly warmer than Plex — right
    # for a regional brand that should feel human without going soft.
    "prairie": "https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&"
               + _PLEX_MONO + "&display=swap",
    # Verification/checklist site. Space Grotesk keeps its technical display
    # character; Plex Sans replaces Inter for body.
    "directory": "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&"
                 "family=IBM+Plex+Sans:wght@400;500;600&" + _PLEX_MONO + "&display=swap",
    # Design-forward reference library. Instrument Serif gives it a real display
    # voice — a magazine needs a headline face, not a heavier weight of the body.
    "editorial": "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&"
                 "family=Space+Grotesk:wght@300;400;500;600;700&" + _PLEX_MONO + "&display=swap",
    # Buyer education. Manrope is friendly and highly legible — kept on purpose;
    # this is the one site where approachability beats severity.
    "guide": "https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&"
             + _PLEX_MONO + "&display=swap",
    # Boutique apothecary. Cormorant + Jost was already the most elegant pairing
    # in the network — left alone.
    "apothecary": "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&"
                  "family=Jost:wght@300;400;500&" + _PLEX_MONO + "&display=swap",
    # Bold metabolic brand. Anton + Archivo is a strong identity — left alone.
    "neon": "https://fonts.googleapis.com/css2?family=Anton&"
            "family=Archivo:ital,wght@0,400;0,600;0,700;0,900;1,900&" + _PLEX_MONO + "&display=swap",
}

# A modern Chrome UA so Google serves woff2 (older/unknown UAs get ttf).
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
# Matches the gstatic woff2 url(...) in Google's @font-face src, quotes optional.
GSTATIC_RE = re.compile(r"""url\(['"]?(https://fonts\.gstatic\.com/[^)'"]+\.woff2)['"]?\)""")


class Command(BaseCommand):
    help = "Download Google Fonts woff2 locally and emit per-theme @font-face CSS."

    def add_arguments(self, parser):
        parser.add_argument("--force", action="store_true",
                            help="Re-download woff2 even if the file already exists.")

    def _get(self, url):
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read()

    def handle(self, *args, **opts):
        static_dir = Path(settings.STATICFILES_DIRS[0])
        fonts_dir = static_dir / "fonts"
        fonts_dir.mkdir(parents=True, exist_ok=True)
        downloaded = reused = themes = 0

        for theme, css_url in THEME_FONTS.items():
            css = self._get(css_url).decode("utf-8")
            urls = list(dict.fromkeys(GSTATIC_RE.findall(css)))  # unique, ordered
            for u in urls:
                name = u.rsplit("/", 1)[-1]
                dest = fonts_dir / name
                if dest.exists() and not opts["force"]:
                    reused += 1
                else:
                    dest.write_bytes(self._get(u))
                    downloaded += 1
                css = css.replace(u, f"{settings.STATIC_URL}fonts/{name}")
            (fonts_dir / f"{theme}.css").write_text(css, encoding="utf-8")
            themes += 1
            self.stdout.write(f"  {theme}: {len(urls)} font file(s)")

        self.stdout.write(self.style.SUCCESS(
            f"webfonts: {themes} theme CSS written, {downloaded} downloaded, "
            f"{reused} reused -> {fonts_dir}"))
