# Generated by Django 5.2.16 on 2026-07-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cost_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="COGS snapshot — sum of unit costs at time of sale.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
