# Generated by Django 5.2 on 2026-07-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_cost_total_orderitem_unit_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interac", "Interac e-Transfer"),
                    ("crypto", "Cryptocurrency"),
                    ("alipay", "Alipay"),
                    ("western_union", "Western Union"),
                    ("other", "Other"),
                ],
                help_text="How the customer chose to pay. All methods are confirmed by hand.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Interac reference, transaction hash, Alipay/WU receipt number.",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="promised_max_days",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="order",
            name="promised_min_days",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(
                blank=True, help_text="Where the manufacturing partner ships to."
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_carrier",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending payment"),
                    ("payment_review", "Payment in review"),
                    ("paid", "Paid"),
                    ("po_sent", "Ordered from supplier"),
                    ("supplier_shipped", "Shipped by supplier"),
                    ("in_transit", "In transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
