# Generated by Django 5.2 on 2026-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_delivered_at_order_paid_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="pack_size",
            field=models.PositiveIntegerField(
                default=1, help_text="Vials per pack at time of order."
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="qty",
            field=models.PositiveIntegerField(default=1, help_text="Packs ordered."),
        ),
    ]
