# Generated by Django 5.2.16 on 2026-07-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("honeypot", "Honeypot trip"),
                            ("ratelimit", "Rate limit hit"),
                            ("bot_trap", "Bot trap URL"),
                            ("bad_signature", "Bad webhook signature"),
                            ("login_failed", "Failed admin login"),
                            ("blocked", "Request blocked"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=300)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "created_at"],
                        name="security_se_kind_c39079_idx",
                    ),
                    models.Index(fields=["ip"], name="security_se_ip_701df4_idx"),
                ],
            },
        ),
    ]
