# Generated by Django 5.2.17 on 2026-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityevent",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
