# Generated by Django 5.2.16 on 2026-07-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e164", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("marketing_opted_out", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Site where first seen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="stores.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Inbound"), ("out", "Outbound")], max_length=3
                    ),
                ),
                ("status", models.CharField(default="completed", max_length=20)),
                ("from_number", models.CharField(max_length=20)),
                ("to_number", models.CharField(max_length=20)),
                ("twilio_sid", models.CharField(blank=True, max_length=64)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("recording_url", models.URLField(blank=True)),
                ("transcript", models.TextField(blank=True)),
                ("transcript_source", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="stores.site",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="comms.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Inbound"), ("out", "Outbound")], max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("received", "Received"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked (opted out)"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("marketing", "Marketing"),
                        ],
                        default="transactional",
                        max_length=14,
                    ),
                ),
                ("from_number", models.CharField(max_length=20)),
                ("to_number", models.CharField(max_length=20)),
                ("body", models.TextField()),
                ("twilio_sid", models.CharField(blank=True, max_length=64)),
                ("error", models.CharField(blank=True, max_length=200)),
                ("ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="comms.contact",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="stores.site",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e164", models.CharField(db_index=True, max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("opt_out", "Opt out"),
                            ("opt_in", "Opt in"),
                            ("help", "Help"),
                        ],
                        max_length=8,
                    ),
                ),
                ("keyword", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stores.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e164", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="MB/SK/AB/… (auto)", max_length=4
                    ),
                ),
                ("sms_enabled", models.BooleanField(default=True)),
                ("voice_enabled", models.BooleanField(default=True)),
                (
                    "greeting",
                    models.TextField(
                        blank=True,
                        default="Thanks for calling. Please leave a message after the tone and we'll get back to you.",
                    ),
                ),
                ("ivr_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a shared network number.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="numbers",
                        to="stores.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voicemail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_number", models.CharField(max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("support", "Support"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("recording_url", models.URLField(blank=True)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("transcript", models.TextField(blank=True)),
                ("listened", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voicemails",
                        to="comms.call",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voicemails",
                        to="comms.contact",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voicemails",
                        to="stores.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IvrOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digit", models.CharField(max_length=1)),
                ("label", models.CharField(max_length=60)),
                (
                    "voicemail_category",
                    models.CharField(default="general", max_length=10),
                ),
                (
                    "number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ivr_options",
                        to="comms.phonenumber",
                    ),
                ),
            ],
            options={
                "ordering": ["digit"],
                "unique_together": {("number", "digit")},
            },
        ),
    ]
