# Generated by Django 5.2.17 on 2026-08-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0005_voice_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceconfig",
            name="operator_callback_e164",
            field=models.CharField(
                blank=True,
                help_text="Mobile that click-to-call rings first before dialling the customer.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="smsconsent",
            name="message_sid",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="smsconsent",
            name="note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="smsconsent",
            name="user_agent",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="smskeywordevent",
            name="message_sid",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="smskeywordevent",
            name="raw_body",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="smskeywordevent",
            name="receiving_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="smskeywordevent",
            name="reply_text",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="twilioverificationtracker",
            name="notes",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="twilioverificationtracker",
            name="number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="voicemail",
            name="tier",
            field=models.CharField(
                blank=True, help_text="AI lead/intent classification.", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="voicemail",
            name="tier_rationale",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="voicemail",
            name="transcript_source",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
