# Generated by Django 5.2.17 on 2026-08-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes — never shown to the customer."
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="lead",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="reviewed_by",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reviewed", "Reviewed"),
                    ("replied", "Replied"),
                    ("closed", "Closed"),
                    ("spam", "Spam"),
                ],
                db_index=True,
                default="new",
                max_length=10,
            ),
        ),
    ]
