# Generated by Django 5.2.16 on 2026-07-19 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "keyword",
                    models.CharField(
                        blank=True, help_text="Target SEO keyword.", max_length=120
                    ),
                ),
                ("excerpt", models.CharField(blank=True, max_length=320)),
                ("body", models.TextField(help_text="Markdown.")),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                (
                    "hero_svg",
                    models.TextField(
                        blank=True, help_text="Inline SVG banner (self-contained)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs_review", "Needs review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="needs_review",
                        max_length=14,
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("pass", "Passed guardrails"),
                            ("flagged", "Flagged — needs fix"),
                        ],
                        default="pass",
                        max_length=8,
                    ),
                ),
                ("compliance_notes", models.TextField(blank=True)),
                ("ai_generated", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="stores.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "unique_together": {("site", "slug")},
            },
        ),
    ]
