# Generated by Django 5.2.17 on 2026-08-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="hero_image",
            field=models.CharField(
                blank=True,
                help_text="URL/path to a real hero image (e.g. /static/blog/blog-1.jpg). Takes precedence over the SVG banner.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="hero_svg",
            field=models.TextField(
                blank=True, help_text="Inline SVG banner (fallback)."
            ),
        ),
    ]
