# Generated by Django 5.2 on 2026-07-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_product_gallery_product_image_product_image_alt_and_more"),
        ("orders", "0004_order_delivered_at_order_paid_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("contact_name", models.CharField(blank=True, max_length=140)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="E.164, e.g. +8613800000000. Used to build the wa.me link.",
                        max_length=40,
                    ),
                ),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        default="email",
                        help_text="Where purchase orders go by default.",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency the supplier invoices us in.",
                        max_length=3,
                    ),
                ),
                (
                    "lead_time_min_days",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Order placed -> delivered to our customer.",
                    ),
                ),
                ("lead_time_max_days", models.PositiveSmallIntegerField(default=15)),
                (
                    "minimum_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="MOQ in the supplier's currency. 0 = none.",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="How we pay them, e.g. 'Alipay on order, 50/50'.",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used when a product has no supplier of its own.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to supplier"),
                            ("confirmed", "Confirmed by supplier"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("problem", "Problem"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("ship_to", models.TextField(blank=True)),
                (
                    "cost_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What we owe the supplier, in their currency.",
                        max_digits=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        help_text="How this PO was actually sent.",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_by", models.CharField(blank=True, max_length=140)),
                (
                    "supplier_reference",
                    models.CharField(
                        blank=True,
                        help_text="Their order number, if they give one.",
                        max_length=140,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=120)),
                ("tracking_carrier", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order",
                        to="orders.order",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=140)),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "line_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="suppliers.purchaseorder",
                    ),
                ),
            ],
        ),
    ]
