# Generated by Django 5.2 on 2026-07-28 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_auto_price_product_price_updated_at_and_more"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base", models.CharField(default="USD", max_length=3)),
                ("quote", models.CharField(default="CAD", max_length=3)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("source", models.CharField(blank=True, max_length=60)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["base", "quote", "-fetched_at"],
                        name="suppliers_f_base_9728e7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "fx_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=140)),
                ("applied_by", models.CharField(default="reprice", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cat_no",
                    models.CharField(
                        help_text="The supplier's own catalogue code, e.g. BC10.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("size", models.CharField(help_text="e.g. 10mg, 10ml", max_length=20)),
                (
                    "pack_size",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Vials per box. 1 for volumes and hardware.",
                    ),
                ),
                (
                    "pack_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of one box, in `currency`.",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("standard", "Standard research compound"),
                            (
                                "patented",
                                "Patent-enforced GLP-1 — legal review required",
                            ),
                            ("hormone", "Regulated hormone — legal review required"),
                            ("consumable", "Consumable or hardware"),
                        ],
                        default="standard",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prices",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "cat_no"],
            },
        ),
    ]
