# Generated by Django 5.2.17 on 2026-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_fxrate_pricechange_supplierprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierprice",
            name="risk",
            field=models.CharField(
                choices=[
                    ("standard", "Standard research compound"),
                    ("patented", "Patent-enforced GLP-1 — legal review required"),
                    ("hormone", "Regulated hormone — legal review required"),
                    ("controlled", "Controlled substance — legal review required"),
                    ("consumable", "Consumable or hardware"),
                ],
                default="standard",
                max_length=12,
            ),
        ),
    ]
