# Generated by Django 5.2.16 on 2026-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Canonical host, e.g. smashfatbiolabs.ca",
                        max_length=190,
                        unique=True,
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Extra hosts that resolve to this site, e.g. ["www.smashfatbiolabs.ca"]',
                    ),
                ),
                ("brand_name", models.CharField(max_length=120)),
                (
                    "theme",
                    models.SlugField(
                        help_text="Theme folder under templates/themes/ + static/themes/",
                        max_length=60,
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("promo_code", models.CharField(blank=True, max_length=30)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("ships_from", models.CharField(default="Canada", max_length=80)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("palette", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["domain"],
            },
        ),
    ]
