# Generated by Django 5.2.16 on 2026-07-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text='Display phone shown in header/hero/footer, e.g. "1-839-BIOLABS".',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="phone_alt",
            field=models.CharField(
                blank=True, help_text="Secondary display phone.", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="phone_alt_tel",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="site",
            name="phone_tel",
            field=models.CharField(
                blank=True,
                help_text='Dialable form for tel: links, e.g. "+18392465227".',
                max_length=40,
            ),
        ),
    ]
