# Generated by Django 5.2 on 2026-07-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_site_phone_site_phone_alt_site_phone_alt_tel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="brand_key",
            field=models.SlugField(
                blank=True,
                help_text="Sites sharing a brand_key are hreflang twins (e.g. the .ca and .com of one brand). Leave blank for a standalone site.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="country",
            field=models.CharField(
                choices=[("CA", "Canada"), ("US", "United States")],
                default="CA",
                help_text="Primary market this domain targets. .ca -> CA, .com -> US.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="currency",
            field=models.CharField(
                choices=[("CAD", "Canadian dollar"), ("USD", "US dollar")],
                default="CAD",
                help_text="Display + schema currency for this storefront.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="shipping_max_days",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="site",
            name="shipping_min_days",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="site",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text='Display phone shown in header/hero/footer, e.g. "1-325-BIOLABS" (owned vanity line).',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="phone_tel",
            field=models.CharField(
                blank=True,
                help_text='Dialable form for tel: links, e.g. "+13252465227".',
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="ships_from",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DEPRECATED — internal note only. Never rendered on the storefront. Orders ship direct from the manufacturing partner, so an origin claim here would be a false representation.",
                max_length=80,
            ),
        ),
    ]
