# Generated by Django 5.2.16 on 2026-07-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                ("color", models.CharField(default="#4f8ff7", max_length=9)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="CAD per vial", max_digits=8
                    ),
                ),
                ("purity", models.CharField(default="≥99%", max_length=20)),
                (
                    "sizes",
                    models.JSONField(default=list, help_text='e.g. ["10mg", "50mg"]'),
                ),
                (
                    "stock",
                    models.CharField(
                        choices=[
                            ("in", "In stock"),
                            ("low", "Low stock"),
                            ("out", "Out of stock"),
                        ],
                        default="in",
                        max_length=3,
                    ),
                ),
                ("is_new", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "coa_url",
                    models.URLField(
                        blank=True, help_text="Link to the batch COA PDF, if any"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
