# Generated by Django 5.2.16 on 2026-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_qty",
            field=models.IntegerField(
                default=0, help_text="Vials on hand (shared across all sites)."
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="track_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.CharField(
                choices=[
                    ("in", "In stock"),
                    ("low", "Low stock"),
                    ("out", "Out of stock"),
                ],
                default="in",
                help_text="Manual status, used only when inventory tracking is off.",
                max_length=3,
            ),
        ),
    ]
