# Generated by Django 5.2.16 on 2026-07-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_low_stock_threshold_product_stock_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Your landed cost per vial (CAD) — used for margin, COGS and inventory value.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="CAD sell price per vial", max_digits=8
            ),
        ),
    ]
