# Generated by Django 5.2.16 on 2026-07-19 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_unit_cost_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="appearance",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="cas_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="product",
            name="faqs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of {"q":..., "a":...} shown on the product page + as FAQ schema.',
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="half_life",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="product",
            name="lab_name",
            field=models.CharField(
                blank=True,
                default="Janoshik Analytical",
                help_text="Independent lab that issued the batch COA.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="lot_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="product",
            name="molecular_formula",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="molecular_weight",
            field=models.CharField(
                blank=True,
                help_text="g/mol, as a display string e.g. 1419.5",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="research_area",
            field=models.TextField(
                blank=True,
                help_text="One compliant sentence — laboratory research framing only.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sequence",
            field=models.TextField(
                blank=True, help_text="Amino-acid sequence / structure note."
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="solubility",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="storage",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="synonyms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=80)),
                ("location", models.CharField(blank=True, max_length=80)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("body", models.TextField()),
                ("is_verified", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateField(help_text="Display date.")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
