# Generated by Django 5.2 on 2026-07-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_appearance_product_cas_number_product_faqs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gallery",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Extra images: [{"src": "/static/...", "alt": "...", "label": "Label detail"}]',
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Primary product image, e.g. /static/products/bpc-157.png",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text. Auto-generated from the product name when blank.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="list_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pre-discount reference price. When set and higher than the sell price, the storefront shows it struck through. Leave blank for no comparison price.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
