# Generated by Django 5.2 on 2026-07-28 18:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_pack_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="auto_price",
            field=models.BooleanField(
                default=False,
                help_text="Recalculate the retail price from cost automatically. Off means the price is whatever a human last set.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_cat_no",
            field=models.CharField(
                blank=True,
                help_text="Supplier catalogue code this product is bought as, e.g. BC10. Links cost and retail price to the supplier price list.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="target_margin_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("75.00"),
                help_text="Gross margin to hold when prices are recalculated from cost.",
                max_digits=5,
            ),
        ),
    ]
