# Generated by Django 5.2 on 2026-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_auto_price_product_price_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="family",
            field=models.SlugField(
                blank=True,
                help_text="Groups sibling strengths into one listing, e.g. 'bpc-157'. Blank means this product stands alone.",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="family_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order within the size selector, smallest first."
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_family_default",
            field=models.BooleanField(
                default=False,
                help_text="The strength shown on the catalogue card and opened by default.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size_label",
            field=models.CharField(
                blank=True,
                help_text="The strength this row represents, e.g. '10mg'. Shown on the size selector.",
                max_length=20,
            ),
        ),
    ]
