# Generated by Django 5.2 on 2026-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_size_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purity",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
