"""Themed password-reset flow, mounted once at /account/ (not namespaced), so
Django's built-in reverse() calls resolve cleanly. Emails go out through the
Mailgun backend. Staff invites reuse the same 'reset confirm' page via a link
generated by the invite_portal_user command / portal action.
"""
from django.contrib.auth import views as av
from django.urls import path, reverse_lazy

urlpatterns = [
    path("password/reset/", av.PasswordResetView.as_view(
        template_name="account/password_reset_form.html",
        email_template_name="account/password_reset_email.txt",
        subject_template_name="account/password_reset_subject.txt",
        success_url=reverse_lazy("password_reset_done"),
    ), name="password_reset"),
    path("password/reset/sent/", av.PasswordResetDoneView.as_view(
        template_name="account/password_reset_done.html",
    ), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", av.PasswordResetConfirmView.as_view(
        template_name="account/password_reset_confirm.html",
        success_url=reverse_lazy("password_reset_complete"),
    ), name="password_reset_confirm"),
    path("reset/done/", av.PasswordResetCompleteView.as_view(
        template_name="account/password_reset_complete.html",
    ), name="password_reset_complete"),
]
